version: "3.2"
services:

# Apache with PHP
  apache:
    build:
      context: './apache-php/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - ${APACHE_EXTERN_PORT}:80
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
      - ./apache-php/conf/demo.apache.conf:/usr/local/apache2/conf/demo.apache.conf
      - ./apache-php/php.ini:/usr/local/etc/php/php.ini
    container_name: apache

  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - ${MYSQL_EXTERN_PORT}:3306
    volumes:
            - ${DB_DATA_PATH}:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_EXTERN_PORT}:80
    environment:
      PMA_HOST: mysql
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      UPLOAD_LIMIT: 5000M
    networks:
      - frontend
      - backend
    container_name: phpmyadmin


networks:
  frontend:
  backend:
volumes:
    data:
